input = [
  98,
  97,
  110,
  105,
  99,
  97,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
]
input_size = 6
hash = [
  47,
  247,
  221,
  125,
  88,
  182,
  4,
  212,
  177,
  153,
  46,
  25,
  133,
  221,
  37,
  195,
  163,
  147,
  112,
  200,
  21,
  244,
  142,
  11,
  119,
  197,
  20,
  70,
  207,
  214,
  76,
  219,
]
