# === mode
test: false

# === features

calltrace: true
flow:
  enabled: true
  # preload flow:
  #   you can have parallel, inline or multiline
  ui: "parallel"
trace: true
events: true
# history: experimental support
history: true
repl: true

traceSharing:
  enabled: true
  # for now local setup
  baseUrl: "http://192.168.8.212:55504/api/codetracer/v1"
  downloadApi: "/download"
  deleteApi: "/delete"
  getUploadUrlApi: "/get/upload/url"

# === feature settings

# orthogonal to calltrace:
#   should we load args/return values for
#   callstack/calltrace
callArgs: true

# enable or disable telemetry:
# if you enable it, it will collect colored logs
#   in your terminal (and comlog.txt) which are visible when you directly ./run.sh id
#   yaml logs in telemetry.log which can be converted back to colored logs with format.js
#   if you have a problem you can send back telemetry.log
#
# MAKE SURE THERE IS NO SENSITIVE INFO IN
# telemetry.log
telemetry: false

# debug message
debug: true

# layout:
#   currently we miss the changed layout: TODO
layout: "default_layout"

# theme:
#   you can also choose default_white or default_dark
theme: "default_dark"

# project open
default: ""

# what commands to use by default for build and update while editing
defaultBuild: ""

# === editor/shortcut settings
showMinimap: true

# # you can use KEY+OTHER
# # use PageUp, PageDown, CTRL, ALT, SHIFT
# # we'll fix it, but for now have to match to two apis and to process it more
bindings:
  forwardContinue: "F8 F2"
  reverseContinue: "SHIFT+F8"
  forwardNext: "F10"
  reverseNext: "SHIFT+F10"
  forwardStep: "F11"
  reverseStep: "SHIFT+F11"
  forwardStepOut: "F12"
  reverseStepOut: "SHIFT+F12"
  stop: "SHIFT+F5"
  build: "CTRL+B"
  switchTabLeft: "CTRL+PageUp"
  switchTabRight: "CTRL+PageDown"
  switchTabHistory: "CTRL+Tab"
  openFile: "CTRL+O"
  newTab: "CTRL+N"
  reopenTab: "CTRL+SHIFT+T"
  closeTab: "CTRL+W"
  goUp: "Up"
  goDown: "Down"
  pageUp: "PageUp"
  pageDown: "PageDown"
  switchDebug: "CTRL+D"
  switchEdit: "CTRL+E"
  fileSearch: "CTRL+P"
  commandSearch: "ALT+P"
  fixedSearch: "CTRL+SHIFT+P"
  goRight: "Right"
  goLeft: "Left"
  gotoStart: "Home"
  gotoEnd: "End"
  aEnter: "Enter"
  aEscape: "Esc"
  findOrFilter: "CTRL+F"
  zoomIn: "CTRL+="
  zoomOut: "CTRL+-"
  example: "CTRL+L"
  aMenu: "CTRL+M"
  aLowLevel1: "ALT+1"
  switchFocusedLoopLevelUp: "CTRL+SHIFT+Q"
  switchFocusedLoopLevelDown: "CTRL+SHIFT+A"
  setFlowTypeToMultiline: "ALT+SHIFT+M"
  setFlowTypeToParallel: "ALT+SHIFT+P"
  setFlowTypeToInline: "ALT+SHIFT+I"
  findInFiles: "CTRL+SHIFT+F"
  findSymbol: "CTRL+T"
  aRestart: "CTRL+F4"

rrBackend:
  enabled: false
  path: ""
  ctPaths: ""
  debugInfoToolPath: ""
  ctRRWorkerExe: ""

skipInstall: true

# TODO: Use this somehow
version: "0.1alpha"